### ISSUE TITLE
Problem under conda, ok if using pip. caching sha2 plug-in missing.

### ISSUE THREAD

**Issue by wrishel** [conda-forge/mysql-connector-python-feedstock#25]
Issue:
If this is in the wrong place, please tell me where to go. It is about an issue that arises when using mysql-connector-python through conda but not through pip and python3 venv.
<br/>
I don't understand the template so I hope I am giving you the information you need. In particular was I supposed to fill in the results of the conda list and conda env commands or will that be done automatically?<br/>
A very simple python program, which does nothing but open a connection, works in the pip/venv environment and fails in the conda environment. I recreated the environments fresh and there are no other modules installed. I am using the Oracle install of MySQL on OSX Catalina.
<br/>
The error message is <code>_mysql_connector.MySQLInterfaceError: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/Users/Wes/opt/miniconda3/envs/ty_db_conda/lib/plugin/caching_sha2_password.so, 2): image not found</code><br/>
In fact the plugin is not present in the directory shown in the error message, although other .so files are there.<br/><br/>
The program is <pre><code>
import mysql.connector as dbase
test_dbconfig = {
    "user": "ETP",
    "password": "Hetp2020",
    "database": "HETPtesting",
    "auth_plugin": 'caching_sha2_password'
}
cnx = dbase.connect(**test_dbconfig)
</code></pre><br/>
As I said the program works if I create a python3 venv, download mysql and mysql.connector.python with pip and run it.<br/>
Environment (<pre><code># packages in environment at /Users/Wes/opt/miniconda3/envs/ty_db_conda:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_1  
cyrus-sasl                2.1.26               hb48c43a_4  
krb5                      1.16.4               hddcf347_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libdb                     6.1.26               h0a44026_0  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libntlm                   1.5                  h1de35cc_0  
libprotobuf               3.6.0                hd9629dc_0  
mysql                     5.7.24               h56848d4_0  
mysql-connector-c         6.1.11               hccea1a4_1  
mysql-connector-python    8.0.18           py37h3febbb0_1  
ncurses                   6.2                  h0a44026_0  
openssl                   1.1.1f               h1de35cc_0  
pip                       20.0.2                   py37_1  
protobuf                  3.6.0            py37h0a44026_0  
python                    3.7.7           hc70fcce_0_cpython  
readline                  8.0                  h1de35cc_0  
setuptools                46.1.3                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
wheel                     0.34.2                   py37_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  </code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda -V
conda 4.8.3
</code> and system ( <code>conda info

     active environment : ty_db_conda
    active env location : /Users/Wes/opt/miniconda3/envs/ty_db_conda
            shell level : 1
       user config file : /Users/Wes/.condarc
 populated config files : /Users/Wes/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __osx=10.15.4
       base environment : /Users/Wes/opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/Wes/opt/miniconda3/pkgs
                          /Users/Wes/.conda/pkgs
       envs directories : /Users/Wes/opt/miniconda3/envs
                          /Users/Wes/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/19.4.0 OSX/10.15.4
                UID:GID : 502:20
             netrc file : /Users/Wes/.netrc
           offline mode : False

</code> </pre>):
<details>

```
$ conda info

```
</details>

**Comment by nehaljwani** [comment]
Blocked on https://github.com/conda-forge/mysql-feedstock/issues/6#issuecomment-623760618

**Comment by nehaljwani** [comment]
Resolved via https://github.com/conda-forge/mysql-connector-python-feedstock/pull/28
