### ISSUE TITLE
Pinning protobuf and requiring libprotobuf

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/mysql-connector-python-feedstock#3]
Seems this is linking to protobuf's C++ libraries, correct? Would be good to add `libprotobuf` as a pinned requirement ( [currently pinned at 3.5]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/7cea2bda28744e48287e6b5d28a53e9a652e39df/recipe/conda_build_config.yaml#L128-L129 ) ) if that is the case.

**Comment by synapticarbors** [comment]
@jakirkham - I just got the latest version of this working after a long period of neglect. Can you tell me or point me at the proper changes that need to be made to pin `libprotobuf` correctly?

**Comment by synapticarbors** [comment]
Does https://github.com/conda-forge/mysql-connector-python-feedstock/pull/13 resolve this issue for you?

**Comment by nehaljwani** [comment]
libprotobuf is being pinned since v8.0.14
