### ISSUE TITLE
Add ppc64le support

### ISSUE THREAD

**Issue by njalerikson** [conda-forge/mysql-connector-python-feedstock#31]
I understand that modern versions of MySQL Connector include a C extension which is what needs to be built on a per arch basis and doesn't appear to be compatible with ppc64le. I also understand that MySQL Connector is still shipped with the pure Python implementation and this is what is available when installing mysql-connector-python from pip.

What needs to be modified here in order for this to be packaged for ppc64le as well?

**Comment by nehaljwani** [comment]
Need a build of mysql-libs for ppc64le to make this happen. I'm giving this a try. Will provide an update by the end of this week.

**Comment by nehaljwani** [comment]
Blocked on https://github.com/conda-forge/mysql-feedstock/pull/17

**Comment by nehaljwani** [comment]
Packages are available now:

```
$ CONDA_SUBDIR=linux-ppc64le conda search conda-forge::mysql-connector-python
Loading channels: done
# Name                       Version           Build  Channel             
mysql-connector-python          8.0.21  py36h45a1f53_0  conda-forge         
mysql-connector-python          8.0.21  py36heb246ff_0  conda-forge         
mysql-connector-python          8.0.21  py37h1954b6c_0  conda-forge         
mysql-connector-python          8.0.21  py38h51173c8_0  conda-forge         
```

**Comment by nehaljwani** [comment]
Resolved via https://github.com/conda-forge/mysql-connector-python-feedstock/pull/32
