### ISSUE TITLE
Unpin protobuf

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/mysql-connector-python-feedstock#80]
The version pinned here is ancient, and causing this feedstock to miss already several protobuf migrations. 3.20 is completely unsupported in conda-forge these days, and so the packages produced here will become less and less installable.

Given that this package has the right dependency on `libprotobuf` (i.e. you can generate whatever protobuf's with the correct version), it's very likely that the upstream pin is completely unnecessary, and just defensive on the side of the upstream developers, because it's really painful to handle on PyPI.

Given that some people want to run `pip check`, this should simply be patched out. Ideally combined with running the upstream test suite, so we ensure everything still works fine.

CC @conda-forge/mysql-connector-python @bollwyvl

**Comment by nehaljwani** [comment]
If the context provided in the commit message of https://github.com/mysql/mysql-connector-python/commit/07e3d17dc4dcea16f79a8e8364328926f0afc9ff is not going to be an issue in the conda-forge ecosystem, feel free to open a pull request :)

**Comment by bollwyvl** [comment]
Agreed that upstream would need to own the underlying issue more fully for it to be fully resolved.

For here: patch and test sounds like a solid way forward. Perhaps with the `extras` as named packages, one could even sneak in a few more test excursions (e.g. epoch versions of protobuf).

**Comment by h-vetinari** [comment]
> If the context provided in the commit message of [mysql/mysql-connector-python@07e3d17](https://github.com/mysql/mysql-connector-python/commit/07e3d17dc4dcea16f79a8e8364328926f0afc9ff) is not going to be an issue in the conda-forge ecosystem, feel free to open a pull request :)

It sounds a bit nonsensical to me. The protobuf python bindings and protoc obviously go together. However 4.21.0 was the very first release with the new protobuf versions scheme, and it might have just been a regular bug as well... I don't know this feedstock, but if there's an upstream test suite to run (and we pass it), I really wouldn't worry. If there's no good test suite, I wouldn't want to risk it though.
